import argparse
import json
import re
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACT_PATH = ROOT / 'tests' / 'htsw_contract.json'
OUT_DIR = ROOT / 'pyhtsw' / 'generated'

HEADER = (
    '# Generated by scripts/gen_types.py from tests/htsw_contract.json. Do not edit.\n'
)

# (alias name, map name, contract enum key). Aliases that would collide with a
# condition or value class carry a Name suffix; the map keeps the bare concept.
ENUMS = (
    ('Gamemode', 'GAMEMODE_TO_HTSW', 'gamemodes'),
    ('HousingColor', 'HOUSING_COLOR_TO_HTSW', 'colors'),
    ('ChatSpeed', 'CHAT_SPEED_TO_HTSW', 'chatSpeeds'),
    ('CommandMode', 'COMMAND_MODE_TO_HTSW', 'commandModes'),
    ('Permission', 'PERMISSION_TO_HTSW', 'permissions'),
    ('EventName', 'EVENT_NAME_TO_HTSW', 'events'),
    ('NpcSkin', 'NPC_SKIN_TO_HTSW', 'npcSkins'),
    ('PotionEffect', 'POTION_EFFECT_TO_HTSW', 'potionEffects'),
    ('Lobby', 'LOBBY_TO_HTSW', 'lobbies'),
    ('ItemProperty', 'ITEM_PROPERTY_TO_HTSW', 'itemProperties'),
    ('ItemLocation', 'ITEM_LOCATION_TO_HTSW', 'itemLocations'),
    ('ItemAmount', 'ITEM_AMOUNT_TO_HTSW', 'itemAmounts'),
    ('EnchantmentName', 'ENCHANTMENT_TO_HTSW', 'enchantments'),
    ('DamageCauseName', 'DAMAGE_CAUSE_TO_HTSW', 'damageCauses'),
    ('FishingEnvironmentName', 'FISHING_ENVIRONMENT_TO_HTSW', 'fishingEnvironments'),
    ('PortalTypeName', 'PORTAL_TYPE_TO_HTSW', 'portalTypes'),
)


# Upstream misspellings the parser insists on: the sane name on our side, the
# exact upstream string on the wire.
SPELLING_FIXES = {
    'Projectile Projection': 'projectile_protection',
}


def snake(value: str) -> str:
    fixed = SPELLING_FIXES.get(value)
    if fixed is not None:
        return fixed
    return re.sub(r'[^A-Za-z0-9]+', '_', value).strip('_').lower()


def snake_pairs(values: list[str], key: str) -> list[tuple[str, str]]:
    pairs = [(snake(value), value) for value in values]
    seen: dict[str, str] = {}
    for name, original in pairs:
        if name in seen:
            raise SystemExit(
                f'{key}: {original!r} and {seen[name]!r} both snake to {name!r}',
            )
        seen[name] = original
    return pairs


def literal_block(name: str, values: list[str]) -> list[str]:
    lines = [f'{name} = Literal[']
    lines += [f'    {value!r},' for value in values]
    lines.append(']')
    return lines


def dict_block(
    name: str,
    annotation: str,
    pairs: Sequence[tuple[object, object]],
) -> list[str]:
    lines = [f'{name}: {annotation} = {{']
    lines += [f'    {key!r}: {value!r},' for key, value in pairs]
    lines.append('}')
    return lines


def render_enums(contract: dict) -> str:
    lines = [HEADER, '# fmt: off', 'from typing import Literal', '']
    for alias, map_name, key in ENUMS:
        pairs = snake_pairs(contract['enums'][key], key)
        lines.append('')
        lines += literal_block(alias, [name for name, _ in pairs])
        lines.append('')
        lines += dict_block(map_name, f'dict[{alias}, str]', pairs)

    gamemodes = [snake(v) for v in contract['enums']['gamemodes']]
    defaults = {snake(v): v for v in contract['enums']['defaultGameModes']}
    if set(gamemodes) != set(defaults):
        raise SystemExit('gamemodes and defaultGameModes no longer align')
    lines.append('')
    lines += dict_block(
        'GAMEMODE_TO_DEFAULT_GAMEMODE',
        'dict[Gamemode, str]',
        [(name, defaults[name]) for name in gamemodes],
    )

    sounds = contract['sounds']
    paths = list(dict.fromkeys(entry['path'] for entry in sounds))
    lines.append('')
    lines += literal_block('Sound', paths)
    lines.append('')
    lines += dict_block(
        'SOUND_NAME_TO_PATH',
        'dict[str, Sound]',
        [(entry['name'], entry['path']) for entry in sounds],
    )

    lines.append('')
    lines += literal_block('MinecraftItem', contract['minecraftItems'])
    lines.append('')
    return '\n'.join(lines)


def render_specs(contract: dict) -> str:
    kinds = sorted(
        {
            field['kind']
            for table in ('actionSpecs', 'conditionSpecs')
            for fields in contract[table].values()
            for field in fields
        },
    )
    lines = [
        HEADER,
        '# fmt: off',
        'from typing import Literal, NamedTuple',
        '',
        '',
    ]
    lines += literal_block('FieldKind', kinds)
    lines += [
        '',
        '',
        'class FieldSpec(NamedTuple):',
        '    name: str',
        '    kind: FieldKind',
        '    optional: bool',
        '',
        '',
        'class PlaceholderSpec(NamedTuple):',
        '    name: str',
        "    value_type: Literal['number', 'string']",
        "    args: Literal['none', 'var', 'teamVar', 'team', 'integerBounds', 'numberBounds']",
    ]
    for name, table in (
        ('ACTION_SPECS', 'actionSpecs'),
        ('CONDITION_SPECS', 'conditionSpecs'),
    ):
        lines += ['', '', f'{name}: dict[str, tuple[FieldSpec, ...]] = {{']
        for kw, fields in contract[table].items():
            lines.append(f'    {kw!r}: (')
            for field in fields:
                lines.append(
                    f'        FieldSpec({field["name"]!r}, {field["kind"]!r},'
                    f' {field["optional"]!r}),',
                )
            lines.append('    ),')
        lines.append('}')
    lines += ['', '', 'PLACEHOLDER_SPECS: tuple[PlaceholderSpec, ...] = (']
    for spec in contract['placeholderSpecs']:
        lines.append(
            f'    PlaceholderSpec({spec["name"]!r}, {spec["valueType"]!r},'
            f' {spec["args"]!r}),',
        )
    lines += [')', '']
    return '\n'.join(lines)


def render_names(contract: dict) -> str:
    lines = [HEADER, '# fmt: off', 'from typing import Literal', '']
    lines.append('')
    lines += literal_block('ActionTypeName', list(contract['actionsToKws']))
    lines.append('')
    lines += literal_block('ConditionTypeName', list(contract['conditionsToKws']))
    for name, key in (
        ('ACTIONS_TO_KWS', 'actionsToKws'),
        ('CONDITIONS_TO_KWS', 'conditionsToKws'),
        ('ACTION_NAMES', 'actionNames'),
        ('CONDITION_NAMES', 'conditionNames'),
        ('OPERATION_SYMBOLS', 'operationSymbols'),
        ('COMPARISON_SYMBOLS', 'comparisonSymbols'),
    ):
        lines.append('')
        lines += dict_block(name, 'dict[str, str]', list(contract[key].items()))
    lines.append('')
    dead = ', '.join(repr(kw) for kw in contract['deadActionKws'])
    lines.append(f'DEAD_ACTION_KWS: frozenset[str] = frozenset(({dead},))')
    shorthands = ', '.join(repr(kw) for kw in contract['shorthands'])
    lines.append(f'SHORTHANDS: tuple[str, ...] = ({shorthands})')
    lines.append('')
    return '\n'.join(lines)


def ruff_pipeline(source: str, path: Path) -> str:
    for cmd in (
        ['ruff', 'check', '--fix', '-q', '--stdin-filename', str(path), '-'],
        ['ruff', 'format', '-q', '--stdin-filename', str(path), '-'],
    ):
        result = subprocess.run(
            cmd,
            cwd=ROOT,
            input=source,
            capture_output=True,
            text=True,
            encoding='utf-8',
            check=False,
        )
        if result.returncode == 2:
            raise RuntimeError(' '.join(cmd) + ': ' + result.stderr.strip())
        if result.stdout:
            source = result.stdout
    return source


def generate(write: bool) -> list[str]:
    contract = json.loads(CONTRACT_PATH.read_text(encoding='utf-8'))
    if contract['contractVersion'] != 2:
        raise SystemExit(
            f'expected contract version 2, found {contract["contractVersion"]}',
        )
    files = {
        OUT_DIR / 'enums.py': render_enums(contract),
        OUT_DIR / 'specs.py': render_specs(contract),
        OUT_DIR / 'names.py': render_names(contract),
    }
    stale = []
    OUT_DIR.mkdir(exist_ok=True)
    init = OUT_DIR / '__init__.py'
    if not init.exists() and write:
        init.write_text('', encoding='utf-8')
    for path, source in files.items():
        source = ruff_pipeline(source, path)
        current = path.read_text(encoding='utf-8') if path.exists() else None
        if current == source:
            continue
        if write:
            path.write_text(source, encoding='utf-8')
        else:
            stale.append(str(path.relative_to(ROOT)))
    return stale


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = generate(write=not args.check)
    if args.check:
        if stale:
            print('stale generated types in:')
            for path in stale:
                print('  ' + path)
            print('\nrun: python scripts/gen_types.py')
            return 1
        print('generated types are up to date')
        return 0
    print('generated pyhtsw/generated/')
    return 0


if __name__ == '__main__':
    sys.exit(main())
